const {getOctokitOptions, GitHub} = require('@actions/github/lib/utils');
const core = require('@actions/core');
const {exec, getExecOutput }= require('@actions/exec');
const github = require('@actions/github');
const fs = require("fs");
const {createPullRequest} = require('octokit-plugin-create-pull-request');

const main = async () => {
  const context = github.context;
  const token = core.getInput('GITHUB_TOKEN');

  const Octokit = GitHub.plugin(createPullRequest);

  const octokit = new Octokit(getOctokitOptions(token));

  const commitMessage = 'Version Packages';

    console.log('Running git status check');
    const versionFiles = await hasGitStatusChanged();
    if (versionFiles.length > 0) {
      
      // TODO: Only include file changes that have been generated by changesets
      // i.e **/Changelog.md ./changeset/* **/package.json


      const {data} = await octokit.createPullRequest({
        ...context.repo,
        title: commitMessage,
        body: getPRDescription(versionFiles),
        head: `changeset-release/main`,
        update: true,
        createWhenEmpty: false,
        changes: [
          {
            commit: commitMessage,
            files: getCommitFiles(versionFiles),
            emptyCommit: false,
          },
        ],
      });

       await octokit.rest.issues.addLabels({
      ...context.repo,
      labels: ['Version Package'],
      issue_number: data.number,
    });



      console.log("Succesfully created/updated PR #", data)
      return data.number;
    
    } else {
       console.log('exiting....')
    }
  
};

async function hasGitStatusChanged(

) {
  const output = await getExecOutput('git', ['status', '--porcelain']);

  return output.stdout;
}

function getCommitFiles(versionFiles) {
  let files = versionFiles.split(/\r?\n/);
  files = files.splice(0, files.length -1);

  const fileObj = files.reduce((obj, fileDetails) => {

    const fileDetailsArray = fileDetails.replace(/^\s+/, "").split(/[ ]/);
    const fileStatusCode = fileDetailsArray[0];
    const fileName = fileDetailsArray.pop();

    console.log(fileDetailsArray);

    return {
      ...obj,
      [fileName]: fileStatusCode === "D" ? "" : getFileContent(fileName)
    };
  }, {});

  return fileObj;
}

function getPRDescription(versionFiles) {
  const introContent = "This PR was opened by the [OSUI Version Package](https://github.com/shopify/online-store-ui/.github/actions/changesets/close-existing-release-pr-action/action.yml) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to main, a fresh Version Package PR will be created.";
  
  let files = versionFiles.split(/\r?\n/);
  files = files.splice(0, files.length -1);
  
  const changelogFiles = files.filter(file => file.includes("CHANGELOG.md"));

  const changelogContent = getFileContent(changelogFiles)
  
  // return `${introContent} ${changelogContent}`;
  return introContent;
}

function getFileContent(fileName){
  return fs.readFileSync(fileName).toString();
}



main().catch((err) => core.setFailed(err.message));