name: 'Create snapshot version'
branding:
  icon: shopping-bag
  colour: green
inputs:
  GITHUB_TOKEN:
    description: 'GitHub access token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'