name: 'Delete branch'
branding:
  icon: shopping-bag
  colour: green
inputs:
  GITHUB_TOKEN:
    description: 'GitHub access token'
    required: true
  BRANCH_REF:
    descripton: 'Branch ref for deletion. Format: `heads/${branch-name} '
    required: true
runs:
  using: 'node16'
  main: 'index.js'