name: 'Create Release Notes'
branding:
  icon: shopping-bag
  colour: green
inputs:
  GITHUB_TOKEN:
    description: 'GitHub access token'
    required: true
  PUSHED_TAG:
    description: 'Latest version tag'
    required: true   
runs:
  using: 'node16'
  main: 'index.js'
