name: 'Create Snapshot comment'
branding:
  icon: shopping-bag
  colour: green
inputs:
  GITHUB_TOKEN:
    description: 'GitHub access token'
    required: true
  ISSUE: 
    description: 'PR number'
    required: true
  SNAPSHOTS:
    description: 'Generated snapshots'
    required: true  
runs:
  using: 'node16'
  main: 'index.js'
