name: Changelog

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened

jobs:
  check:
    if: |
      !contains(github.event.pull_request.head.ref, 'changeset-release') &&
      !contains(github.event.pull_request.labels.*.name, 'skip changelog')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node with v16.13.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Check for Changeset
        id: check-for-changeset
        continue-on-error: true
        run: npx @changesets/cli status --since="origin/main"

      - name: Install Dependencies for osui-github actions
        id: install-action-dependencies
        if: steps.check-for-changeset.outcome == 'failure'
        working-directory: .github/actions
        run: yarn install --frozen-lockfile

      - name: Post PR comment
        if: steps.check-for-changeset.outcome == 'failure'
        uses: ./.github/actions/create-pr-comment
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.pull_request.number }}
          MESSAGE: "###  ⚠️  No Changeset found ⚠️ \n\n Merging this PR will not cause a version bump for any packages. 
          If these changes should not result in a new version, please add the `skip changelog` label. \n\n 
          **If these changes should result in a version bump, please run `yarn changeset` to add a changeset.** \n\n 
          Take a look at our [documentation](https://github.com/Shopify/online-store-ui/tree/main/.changeset) to understand how we use changesets in online-store-ui"
         
