name: Release Notes

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]@*'
      - '!v[0-9]+.[0-9]+.[0-9]-snapshot-release-*'


jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies for create-release-notes
        working-directory: ./github/actions/create-release-notes
        run: yarn install --frozen-lockfile

      - name: Create release notes
        uses: ./github/actions/create-release-notes/action.yml
        with:
          PUSHED_TAG: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
