name: Release Notes

on:
  push:
    tags:
      # tag with format 'vx.x.x@repo/pkgname'
      # - '^v\d+\.\d+\.\d+@[\w\-]+/[\w\-]+$'
      - v*

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies for create-update-release-pr-action
        working-directory: .github/actions/create-release-notes
        run: yarn install --frozen-lockfile

      - name: Create release notes
        uses: ./github/actions/create-release-notes/action.yml
        with:
          PUSHED_TAG: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
